language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
deploy:
  provider: lambda
  function_name: alexa_drag_queen_facts
  region: eu-west-1
  role: arn:aws:iam::040251125443:role/service-role/alexa
  runtime: nodejs6.10
  handler_name: handler
  module_name: src/main
  access_key_id: AKIAIINQ4MNAYCPEHGLQ
  secret_access_key:
    secure: t0uZW2qvgQfQDTUgesaUqwl6ZDLvi1ik0C3oix0GjjzXpPzL3N0inDKVc2XuDVzqOc/uNMuxHPhP2cYbhGZqrZgPMUzdZeh5boDyG3cW5/RB+DGpO4RRV6mI16/wqF1Xu9TStf0eqGmkXxnQcbWNxAgGQqWNQsRiLZL+98RW2RsBgpactkBk/LaPkpqJjEX0JTktNlnyU4wxtSK9HxXmGXF8RR/FI1vTXsP66MAHuKXC6i7TtBvfnvBym2+pKra6HWiBGpq3MJnuFR/K8oua5VBKe7er0HdNqX0yaUBLt60NVJ1x0hGjeEHc8rFEUcfIQ8iigeJUyuUhlYXxgGyNIAK2pNDfwfZkQFLtEw1Ey+6jAU0w1gdL3kpXDjQpEd4kGaYSmuWElmNJHHSvFVfSmhfM6R+d7FrKmflpy+Z/sC3kREUH4Rs29+dCVxFmwp3TpCMclDdQcsNQub4GX0/Arii0clQF05vWcDZ3WSFZtSbsYXXfGUGG0BeNkRnAGQq6J/b7kAz6LB9lgNdiMOMDRKmNnvSjN0GTkfZzoggdamlSNtnkhg09on7y6m+hYHDUteYp6eZ4FwxvWa8t0nPi35RjXCrUWhucBrW4LSQyHIyru42AoTGxBVpkTFdh8gP/cGbTWTTH/iMRjVSAo5u9NiAb+s1TCv6TXrwiPsagYI8=
env:
  secure: gH7z03IQkQwbCDvSbauk9BmshJLS3hkNDv7GjqkPreWcrE4bwWLmBzlus6XyncKKoBdMBFVTzDhUyx0pG96kqlRhLPmOtPpSo1MuN1bEUtq9OGFGuecdDeJAZPSXkr3rko01FLPXBPPVCJP0QtDPMGdTAu1/TL2UO+sIYtP5Yfk5zIKuEsdNAzLpmVIbDomSUXcLjpjwdaS//ZkaY1f1f0gFEs6NKQnM4YYUBt/YMXfutzCLw4YecNiZVdY6F+dqe6VimGxLK2iyrAsQZy/eo73Bx5bpNBqcWR0HTlvyXWpP26I12igPsJgXW6zsuExM9dbW6SXXtruDFp8yJ6SmmTs6iLjFxl43y7ZqHwYpZKx7l/0R2ziZpeZh8CUYrp8Tr04gQWP4tg7EFFokeCR0BCOyYfbUErOCKXuRz8vL3ejKBA++wtz5jW3bDUKI9k44jhzT7+ZDMmu5ze4KXyoFpHd9ntj1BNVSMxn53BjudxPmUEME12BrehsXd5w5bvn9vfAQuEIEwzLGTiif/TwKYBj2SMaRBNGhM++7bx0z3sB8/m7NF5G7t6lIg7rS3ilbLrkfAKF+favMDWnAeJorai6SGZRP2Fc6I/ErT6j5qaLL+llBF69Wn0Kg5Y9LgrdSsApApRGWiFkjtEyLnklptYow88zZPVLZna7FSCSZNpM=
