language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_script:
- echo "Preparing to send code coverage reports"
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_success:
- echo "Sending code coverage reports"
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: lambda
  publish: true
  function_name: alexa_drag_queen_facts
  region: eu-west-1
  role: arn:aws:iam::040251125443:role/service-role/alexa
  runtime: nodejs6.10
  handler_name: handler
  module_name: src/main
  access_key_id: AKIAIINQ4MNAYCPEHGLQ
  secret_access_key:
    secure: t0uZW2qvgQfQDTUgesaUqwl6ZDLvi1ik0C3oix0GjjzXpPzL3N0inDKVc2XuDVzqOc/uNMuxHPhP2cYbhGZqrZgPMUzdZeh5boDyG3cW5/RB+DGpO4RRV6mI16/wqF1Xu9TStf0eqGmkXxnQcbWNxAgGQqWNQsRiLZL+98RW2RsBgpactkBk/LaPkpqJjEX0JTktNlnyU4wxtSK9HxXmGXF8RR/FI1vTXsP66MAHuKXC6i7TtBvfnvBym2+pKra6HWiBGpq3MJnuFR/K8oua5VBKe7er0HdNqX0yaUBLt60NVJ1x0hGjeEHc8rFEUcfIQ8iigeJUyuUhlYXxgGyNIAK2pNDfwfZkQFLtEw1Ey+6jAU0w1gdL3kpXDjQpEd4kGaYSmuWElmNJHHSvFVfSmhfM6R+d7FrKmflpy+Z/sC3kREUH4Rs29+dCVxFmwp3TpCMclDdQcsNQub4GX0/Arii0clQF05vWcDZ3WSFZtSbsYXXfGUGG0BeNkRnAGQq6J/b7kAz6LB9lgNdiMOMDRKmNnvSjN0GTkfZzoggdamlSNtnkhg09on7y6m+hYHDUteYp6eZ4FwxvWa8t0nPi35RjXCrUWhucBrW4LSQyHIyru42AoTGxBVpkTFdh8gP/cGbTWTTH/iMRjVSAo5u9NiAb+s1TCv6TXrwiPsagYI8=
  on:
    tags: true
  environment_variables:
  - ENVIRONMENT=production
  - secure: "YwBd4ZGhd49oXxCsI6qsbvrkXZEfABUnJ1VSFfCoxpkV46UC3HSeLSe6HrLXmqdPCt+USbt3h1geA1KvrHlbuhTGVnL+vnrmQnE3NZYtskTaHC76Z4Adnn/jLmrzUN09cVRQN5jyhQalfWAxrHmqjdC01f/6q+Y8u2TDCyVkZPf6x7x6f9h1a5609SAUsbvLP3wKjEHvCyorLxgJH9Mo1HNWKJ8MDKXJUUvqjbey9up829rUIZqIXyQDjf1iqoZxNj8r3/pLQIcGAMqXgy2+cqT4QWbZqOe4/9G2Naf/0W5OfCcOFXxTwp1YIQmIMzIUeVXBXjqHeeIrVu2Jz7bxoSdLPwaBi70wdNzHnoyerhvpogNDCuR/l1zcECbeMAbo07Vb8CqCvkFoQAKWiPYBUDuNKAIr5nRc0cIslYBHu/FWGUtGpLlLUKwjycixJuZN3O7dxYKVYjQpijgTT3LH1vpcMmtmknx1EiMiPjEW6HYifPxJsUeUwiQAbBFLsYP57BmlGtHQ7li3GC8gWUxTB627Kf4qQ9uw84AAKvuBv5Vb7Y5DIUmUvrV/nkytSgb3JCBDMWqPAWt3K6nsb3Yux9iD8AaHVJeykAhQs4S/ZJbq6PAejLRrc1PVPeey3gVJnKPK1KeLwwM3mvWU3Dzch8TxKMOF9EdTiiobmcLbpM4="
  - secure: "KiiX3P++yfULyjoB1PjJY5KSWLw5BQQZ8NtQCWyIM8RQgIFaCkIj3dQBBWl5p9ScaIT5zxYk/DDknnMaKWod936HM2xSV4p+8CBkG1wyBCiPgG30AGy8t6W1Ju3oFANcDRTXcSC9yHNr6NWBvd2w0ScI8INsEO1BzUsp3/3jclbFr104MlgjyHxPqtDLFL6C9POSrhzcVIZODiUfmOJaQ8rlJ3xpRT/PdVJrq4KhkKbh2vhbgrQQBcFcfxFWZDBXKAoohSbhubRksbU3zRRiXewupfZ6N5pEe5xQJEzc6dcgH/ZAHOorByvl1B2tfcLBpxHgJ4809QIOc0ZydAj95KYey9A/a9iuUS7Iwwp1dc1gptRYmkWjY4SR/IvgFqlcP8Kb4nLVmAgV0uqvQN4RIUBihoCAN7aP4iLAV98vdUnHxgYr1nr+jLoLs3iB1Su7Fyqr1YcdbR/khX/SYhfZH81f/+FPAKH0l/0pp7numZ0tZKpub/mJ3/weYmzkKZcBhuxEXcZNcSAU0B0EBE4uXc6iqcT6OLOp8rhqX4cfn8bnnz9y3kJwNk3irvvwTG1FsdcO9ObGvIqDw+/LzcS7VK62aK/pgfTy5vjhNC48mMoa9GvAqubEs/qg4yAWv7t+Ne12rfnxXYUB+K4MQz3IZ+7I5hFtugP2hh634PMarFI="
after_deploy:
- echo "Sending deployment update to AirBrake"
- ACCESS_TOKEN=$ROLLBAR_TOKEN
- ENVIRONMENT=production
- REVISION=`git log -n 1 --pretty=format:"%H"`
- curl https://api.rollbar.com/api/1/deploy/ \
  -F access_token=$ACCESS_TOKEN \
  -F environment=$ENVIRONMENT \
  -F revision=$REVISION \
env:
  global:
  - ENVIRONMENT=development
  - CC_TEST_REPORTER_ID=a4bdae5ee19b3ad7daf91ed0927518a1ff532b0da6f29348ae3a392c50b16d32
  - secure: gH7z03IQkQwbCDvSbauk9BmshJLS3hkNDv7GjqkPreWcrE4bwWLmBzlus6XyncKKoBdMBFVTzDhUyx0pG96kqlRhLPmOtPpSo1MuN1bEUtq9OGFGuecdDeJAZPSXkr3rko01FLPXBPPVCJP0QtDPMGdTAu1/TL2UO+sIYtP5Yfk5zIKuEsdNAzLpmVIbDomSUXcLjpjwdaS//ZkaY1f1f0gFEs6NKQnM4YYUBt/YMXfutzCLw4YecNiZVdY6F+dqe6VimGxLK2iyrAsQZy/eo73Bx5bpNBqcWR0HTlvyXWpP26I12igPsJgXW6zsuExM9dbW6SXXtruDFp8yJ6SmmTs6iLjFxl43y7ZqHwYpZKx7l/0R2ziZpeZh8CUYrp8Tr04gQWP4tg7EFFokeCR0BCOyYfbUErOCKXuRz8vL3ejKBA++wtz5jW3bDUKI9k44jhzT7+ZDMmu5ze4KXyoFpHd9ntj1BNVSMxn53BjudxPmUEME12BrehsXd5w5bvn9vfAQuEIEwzLGTiif/TwKYBj2SMaRBNGhM++7bx0z3sB8/m7NF5G7t6lIg7rS3ilbLrkfAKF+favMDWnAeJorai6SGZRP2Fc6I/ErT6j5qaLL+llBF69Wn0Kg5Y9LgrdSsApApRGWiFkjtEyLnklptYow88zZPVLZna7FSCSZNpM=
  - secure: "YwBd4ZGhd49oXxCsI6qsbvrkXZEfABUnJ1VSFfCoxpkV46UC3HSeLSe6HrLXmqdPCt+USbt3h1geA1KvrHlbuhTGVnL+vnrmQnE3NZYtskTaHC76Z4Adnn/jLmrzUN09cVRQN5jyhQalfWAxrHmqjdC01f/6q+Y8u2TDCyVkZPf6x7x6f9h1a5609SAUsbvLP3wKjEHvCyorLxgJH9Mo1HNWKJ8MDKXJUUvqjbey9up829rUIZqIXyQDjf1iqoZxNj8r3/pLQIcGAMqXgy2+cqT4QWbZqOe4/9G2Naf/0W5OfCcOFXxTwp1YIQmIMzIUeVXBXjqHeeIrVu2Jz7bxoSdLPwaBi70wdNzHnoyerhvpogNDCuR/l1zcECbeMAbo07Vb8CqCvkFoQAKWiPYBUDuNKAIr5nRc0cIslYBHu/FWGUtGpLlLUKwjycixJuZN3O7dxYKVYjQpijgTT3LH1vpcMmtmknx1EiMiPjEW6HYifPxJsUeUwiQAbBFLsYP57BmlGtHQ7li3GC8gWUxTB627Kf4qQ9uw84AAKvuBv5Vb7Y5DIUmUvrV/nkytSgb3JCBDMWqPAWt3K6nsb3Yux9iD8AaHVJeykAhQs4S/ZJbq6PAejLRrc1PVPeey3gVJnKPK1KeLwwM3mvWU3Dzch8TxKMOF9EdTiiobmcLbpM4="
