theme: jekyll-theme-cayman
title: Drag Race Facts
description: Alexa, shantay you stay! 👠
logo: assets/logo.png
links:
  USA: https://www.amazon.com/calum-Drag-Race-Facts/dp/B076Z4KQ57
  UK: https://www.amazon.co.uk/calum-drag-race-facts/dp/B076Z4KQ57
  AUS: https://www.amazon.com.au/calum-Drag-Race-Facts/dp/B076Z4KQ57
  CAN: https://www.amazon.ca/calum-Drag-Race-Facts/dp/B076Z4KQ57
